# Generated by Django 4.2.4 on 2023-08-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domains',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
    ]
